version: "3"
services:
    webserver:
        build: ./local-server
        ports: 
            - "127.0.0.1:8443:443"
            - "127.0.0.1:8080:80"
        volumes:
            - "./local-server/webroot:/var/www/html"
            - "./data:/var/www/data"
